on:
  pull_request_target:
    types:
      - opened
    paths:
      - "tutorial/retrospectives/**/*.yaml"

jobs:
  clean-issue:
    runs-on: ubuntu-latest

    steps:
      - uses: oss-gate/issue-cleaner@v3
        with:
          author: ${{ github.event.sender.login }}
        env:
          DOORKEEPER_TOKEN: ${{ secrets.DOORKEEPER_TOKEN }}
